CREATE TABLE IF NOT EXISTS ER_DEMO.PUBLIC.RAG_CHAT_MEMORY (
    id INTEGER AUTOINCREMENT PRIMARY KEY,
    session_id VARCHAR NOT NULL,
    role VARCHAR NOT NULL,
    message VARCHAR NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)