-- ============================================================================
-- 03_setup_semantic_views.sql
-- Creates Semantic Views for Cortex Analyst tools
-- Reference: https://docs.snowflake.com/en/sql-reference/sql/create-semantic-view
-- ============================================================================

USE DATABASE CUSTOMER_INTELLIGENCE_DB;
USE SCHEMA PUBLIC;

-- ============================================================================
-- CUSTOMER_BEHAVIOR_ANALYST Semantic View
-- Used by: DATA_ANALYST_AGENT
-- ============================================================================

CREATE OR REPLACE SEMANTIC VIEW CUSTOMER_BEHAVIOR_ANALYST
  TABLES (
    CUSTOMERS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.CUSTOMERS
      PRIMARY KEY (CUSTOMER_ID)
      COMMENT = 'Customer master data',
    USAGE_EVENTS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.USAGE_EVENTS
      COMMENT = 'Customer usage events',
    SUPPORT_TICKETS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.SUPPORT_TICKETS
      COMMENT = 'Support tickets',
    CHURN_EVENTS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.CHURN_EVENTS
      COMMENT = 'Churn events'
  )
  RELATIONSHIPS (
    CUSTOMER_TO_USAGE AS USAGE_EVENTS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CUSTOMER_TO_SUPPORT AS SUPPORT_TICKETS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CUSTOMER_TO_CHURN AS CHURN_EVENTS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
  )
  FACTS (
    CUSTOMERS.MONTHLY_REVENUE AS CUSTOMERS.MONTHLY_REVENUE
      WITH SYNONYMS = ('MRR', 'monthly recurring revenue')
      COMMENT = 'Monthly revenue per customer',
    USAGE_EVENTS.SESSION_DURATION_MINUTES AS USAGE_EVENTS.SESSION_DURATION_MINUTES
      WITH SYNONYMS = ('session length')
      COMMENT = 'Session duration in minutes',
    USAGE_EVENTS.ACTIONS_COUNT AS USAGE_EVENTS.ACTIONS_COUNT
      COMMENT = 'Number of actions in session',
    SUPPORT_TICKETS.RESOLUTION_TIME_HOURS AS SUPPORT_TICKETS.RESOLUTION_TIME_HOURS
      COMMENT = 'Hours to resolve ticket',
    SUPPORT_TICKETS.SATISFACTION_SCORE AS SUPPORT_TICKETS.SATISFACTION_SCORE
      WITH SYNONYMS = ('CSAT')
      COMMENT = 'Customer satisfaction score',
    CHURN_EVENTS.DAYS_SINCE_SIGNUP AS CHURN_EVENTS.DAYS_SINCE_SIGNUP
      COMMENT = 'Days customer was active',
    CHURN_EVENTS.FINAL_MONTHLY_REVENUE AS CHURN_EVENTS.FINAL_MONTHLY_REVENUE
      COMMENT = 'Revenue at time of churn'
  )
  DIMENSIONS (
    CUSTOMERS.CUSTOMER_ID AS CUSTOMERS.CUSTOMER_ID
      WITH SYNONYMS = ('customer identifier', 'account id')
      COMMENT = 'Unique customer identifier',
    CUSTOMERS.COMPANY_SIZE AS CUSTOMERS.COMPANY_SIZE
      WITH SYNONYMS = ('business size')
      COMMENT = 'Company size: small, medium, large',
    CUSTOMERS.INDUSTRY AS CUSTOMERS.INDUSTRY
      WITH SYNONYMS = ('sector', 'vertical')
      COMMENT = 'Customer industry',
    CUSTOMERS.PLAN_TYPE AS CUSTOMERS.PLAN_TYPE
      WITH SYNONYMS = ('subscription', 'tier')
      COMMENT = 'Subscription plan level',
    CUSTOMERS.STATUS AS CUSTOMERS.STATUS
      COMMENT = 'Customer status: active or churned',
    CUSTOMERS.SIGNUP_DATE AS CUSTOMERS.SIGNUP_DATE
      COMMENT = 'Customer signup date',
    USAGE_EVENTS.EVENT_ID AS USAGE_EVENTS.EVENT_ID
      COMMENT = 'Usage event identifier',
    USAGE_EVENTS.CUSTOMER_ID AS USAGE_EVENTS.CUSTOMER_ID
      COMMENT = 'Customer for usage event',
    USAGE_EVENTS.FEATURE_USED AS USAGE_EVENTS.FEATURE_USED
      WITH SYNONYMS = ('product feature')
      COMMENT = 'Feature used in session',
    USAGE_EVENTS.EVENT_DATE AS USAGE_EVENTS.EVENT_DATE
      COMMENT = 'Date of usage event',
    SUPPORT_TICKETS.TICKET_ID AS SUPPORT_TICKETS.TICKET_ID
      COMMENT = 'Support ticket identifier',
    SUPPORT_TICKETS.CUSTOMER_ID AS SUPPORT_TICKETS.CUSTOMER_ID
      COMMENT = 'Customer for ticket',
    SUPPORT_TICKETS.CATEGORY AS SUPPORT_TICKETS.CATEGORY
      WITH SYNONYMS = ('ticket type')
      COMMENT = 'Ticket category',
    SUPPORT_TICKETS.PRIORITY AS SUPPORT_TICKETS.PRIORITY
      COMMENT = 'Ticket priority',
    SUPPORT_TICKETS.STATUS AS SUPPORT_TICKETS.STATUS
      COMMENT = 'Ticket status',
    SUPPORT_TICKETS.CREATED_DATE AS SUPPORT_TICKETS.CREATED_DATE
      COMMENT = 'Ticket creation date',
    CHURN_EVENTS.CHURN_ID AS CHURN_EVENTS.CHURN_ID
      COMMENT = 'Churn event identifier',
    CHURN_EVENTS.CUSTOMER_ID AS CHURN_EVENTS.CUSTOMER_ID
      COMMENT = 'Churned customer',
    CHURN_EVENTS.CHURN_REASON AS CHURN_EVENTS.CHURN_REASON
      WITH SYNONYMS = ('cancellation reason')
      COMMENT = 'Reason for churn',
    CHURN_EVENTS.CHURN_DATE AS CHURN_EVENTS.CHURN_DATE
      COMMENT = 'Date of churn'
  )
  METRICS (
    CUSTOMERS.TOTAL_CUSTOMERS AS COUNT(CUSTOMERS.CUSTOMER_ID)
      WITH SYNONYMS = ('customer count')
      COMMENT = 'Total number of customers',
    CUSTOMERS.ACTIVE_CUSTOMERS AS COUNT(CASE WHEN CUSTOMERS.STATUS = 'active' THEN CUSTOMERS.CUSTOMER_ID END)
      COMMENT = 'Number of active customers',
    CUSTOMERS.ARPU AS AVG(CUSTOMERS.MONTHLY_REVENUE)
      WITH SYNONYMS = ('average revenue per user')
      COMMENT = 'Average revenue per customer',
    USAGE_EVENTS.AVG_SESSION_DURATION AS AVG(USAGE_EVENTS.SESSION_DURATION_MINUTES)
      COMMENT = 'Average session duration',
    SUPPORT_TICKETS.AVG_RESOLUTION_TIME AS AVG(SUPPORT_TICKETS.RESOLUTION_TIME_HOURS)
      COMMENT = 'Average ticket resolution time',
    SUPPORT_TICKETS.AVG_SATISFACTION AS AVG(SUPPORT_TICKETS.SATISFACTION_SCORE)
      COMMENT = 'Average customer satisfaction',
    CHURN_EVENTS.TOTAL_CHURNED AS COUNT(CHURN_EVENTS.CUSTOMER_ID)
      COMMENT = 'Total churned customers',
    CHURN_EVENTS.AVG_LIFETIME AS AVG(CHURN_EVENTS.DAYS_SINCE_SIGNUP)
      COMMENT = 'Average customer lifetime'
  )
  COMMENT = 'Customer behavior analytics for usage patterns, churn analysis, and retention insights';

-- ============================================================================
-- STRATEGIC_RESEARCH_ANALYST Semantic View  
-- Used by: RESEARCH_AGENT
-- ============================================================================

CREATE OR REPLACE SEMANTIC VIEW STRATEGIC_RESEARCH_ANALYST
  TABLES (
    CUSTOMERS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.CUSTOMERS
      PRIMARY KEY (CUSTOMER_ID)
      COMMENT = 'Customer master data',
    USAGE_EVENTS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.USAGE_EVENTS
      COMMENT = 'Usage data',
    SUPPORT_TICKETS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.SUPPORT_TICKETS
      COMMENT = 'Support data',
    CHURN_EVENTS AS CUSTOMER_INTELLIGENCE_DB.PUBLIC.CHURN_EVENTS
      COMMENT = 'Churn data'
  )
  RELATIONSHIPS (
    CUSTOMER_TO_USAGE AS USAGE_EVENTS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CUSTOMER_TO_SUPPORT AS SUPPORT_TICKETS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID),
    CUSTOMER_TO_CHURN AS CHURN_EVENTS (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
  )
  FACTS (
    CUSTOMERS.MONTHLY_REVENUE AS CUSTOMERS.MONTHLY_REVENUE
      COMMENT = 'Monthly recurring revenue',
    USAGE_EVENTS.SESSION_DURATION_MINUTES AS USAGE_EVENTS.SESSION_DURATION_MINUTES
      COMMENT = 'Session duration',
    USAGE_EVENTS.ACTIONS_COUNT AS USAGE_EVENTS.ACTIONS_COUNT
      COMMENT = 'Actions per session',
    SUPPORT_TICKETS.RESOLUTION_TIME_HOURS AS SUPPORT_TICKETS.RESOLUTION_TIME_HOURS
      COMMENT = 'Resolution time',
    SUPPORT_TICKETS.SATISFACTION_SCORE AS SUPPORT_TICKETS.SATISFACTION_SCORE
      COMMENT = 'Satisfaction score',
    CHURN_EVENTS.DAYS_SINCE_SIGNUP AS CHURN_EVENTS.DAYS_SINCE_SIGNUP
      COMMENT = 'Customer tenure',
    CHURN_EVENTS.FINAL_MONTHLY_REVENUE AS CHURN_EVENTS.FINAL_MONTHLY_REVENUE
      COMMENT = 'Lost revenue'
  )
  DIMENSIONS (
    CUSTOMERS.CUSTOMER_ID AS CUSTOMERS.CUSTOMER_ID
      COMMENT = 'Customer identifier',
    CUSTOMERS.COMPANY_SIZE AS CUSTOMERS.COMPANY_SIZE
      COMMENT = 'Company size',
    CUSTOMERS.INDUSTRY AS CUSTOMERS.INDUSTRY
      WITH SYNONYMS = ('sector', 'vertical', 'market segment')
      COMMENT = 'Industry vertical',
    CUSTOMERS.PLAN_TYPE AS CUSTOMERS.PLAN_TYPE
      COMMENT = 'Subscription tier',
    CUSTOMERS.STATUS AS CUSTOMERS.STATUS
      COMMENT = 'Account status',
    CUSTOMERS.SIGNUP_DATE AS CUSTOMERS.SIGNUP_DATE
      COMMENT = 'Acquisition date',
    USAGE_EVENTS.EVENT_ID AS USAGE_EVENTS.EVENT_ID
      COMMENT = 'Event identifier',
    USAGE_EVENTS.CUSTOMER_ID AS USAGE_EVENTS.CUSTOMER_ID
      COMMENT = 'Customer',
    USAGE_EVENTS.FEATURE_USED AS USAGE_EVENTS.FEATURE_USED
      COMMENT = 'Feature used',
    USAGE_EVENTS.EVENT_DATE AS USAGE_EVENTS.EVENT_DATE
      COMMENT = 'Event date',
    SUPPORT_TICKETS.TICKET_ID AS SUPPORT_TICKETS.TICKET_ID
      COMMENT = 'Ticket identifier',
    SUPPORT_TICKETS.CUSTOMER_ID AS SUPPORT_TICKETS.CUSTOMER_ID
      COMMENT = 'Customer',
    SUPPORT_TICKETS.CATEGORY AS SUPPORT_TICKETS.CATEGORY
      COMMENT = 'Issue category',
    SUPPORT_TICKETS.PRIORITY AS SUPPORT_TICKETS.PRIORITY
      COMMENT = 'Priority level',
    SUPPORT_TICKETS.STATUS AS SUPPORT_TICKETS.STATUS
      COMMENT = 'Ticket status',
    SUPPORT_TICKETS.CREATED_DATE AS SUPPORT_TICKETS.CREATED_DATE
      COMMENT = 'Creation date',
    CHURN_EVENTS.CHURN_ID AS CHURN_EVENTS.CHURN_ID
      COMMENT = 'Churn identifier',
    CHURN_EVENTS.CUSTOMER_ID AS CHURN_EVENTS.CUSTOMER_ID
      COMMENT = 'Churned customer',
    CHURN_EVENTS.CHURN_REASON AS CHURN_EVENTS.CHURN_REASON
      COMMENT = 'Churn reason',
    CHURN_EVENTS.CHURN_DATE AS CHURN_EVENTS.CHURN_DATE
      COMMENT = 'Churn date'
  )
  METRICS (
    CUSTOMERS.TOTAL_CUSTOMERS AS COUNT(CUSTOMERS.CUSTOMER_ID)
      COMMENT = 'Total customers',
    CUSTOMERS.ACTIVE_CUSTOMERS AS COUNT(CASE WHEN CUSTOMERS.STATUS = 'active' THEN CUSTOMERS.CUSTOMER_ID END)
      COMMENT = 'Active customers',
    CUSTOMERS.TOTAL_MRR AS SUM(CUSTOMERS.MONTHLY_REVENUE)
      WITH SYNONYMS = ('total recurring revenue')
      COMMENT = 'Total monthly recurring revenue',
    USAGE_EVENTS.AVG_SESSION AS AVG(USAGE_EVENTS.SESSION_DURATION_MINUTES)
      COMMENT = 'Average session duration',
    USAGE_EVENTS.ACTIVE_USERS AS COUNT(DISTINCT USAGE_EVENTS.CUSTOMER_ID)
      COMMENT = 'Unique active users',
    SUPPORT_TICKETS.AVG_RESOLUTION AS AVG(SUPPORT_TICKETS.RESOLUTION_TIME_HOURS)
      COMMENT = 'Average resolution time',
    CHURN_EVENTS.CHURNED_COUNT AS COUNT(CHURN_EVENTS.CUSTOMER_ID)
      COMMENT = 'Churned customers',
    CHURN_EVENTS.LOST_REVENUE AS SUM(CHURN_EVENTS.FINAL_MONTHLY_REVENUE)
      COMMENT = 'Total lost revenue'
  )
  COMMENT = 'Strategic research and market intelligence for executive-level business analysis';

-- ============================================================================
-- VERIFY
-- ============================================================================
SHOW SEMANTIC VIEWS IN SCHEMA CUSTOMER_INTELLIGENCE_DB.PUBLIC;

